name: aplikasi_mewarnai
description: Aplikasi mewarnai sederhana

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bunga.jpg
    - assets/images/rumah.jpg
    - assets/images/mobil.jpg
